/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.ManagementRole;

import Business.Enterprise.Enterprise;
import Business.Enterprise.EnterpriseDirectory;
import Business.Government;
import Business.Network.Network;
import Business.Organization.Organization;
import Business.Organization.OrganizationDirectory;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author kanikamakhija
 */
public class ManagementMainJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ManagementMainJPanel
     */
    private JPanel userProcessContainer;
    private Organization organization;
    private final Network network;
    private final UserAccount userAccount;
    private final Enterprise enterprise;
    private final Government govt;
    
    public ManagementMainJPanel(JPanel userProcessContainer, Organization organization, Enterprise enterprise, Network network, UserAccount userAccount, Government govt) {
        initComponents();
        this.userProcessContainer=userProcessContainer;
        this.organization=organization;
        this.network = network;
        this.userAccount = userAccount;
        this.enterprise = enterprise;
        this.govt = govt;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnMaintenanceRequests = new javax.swing.JButton();
        btnCheckAgentReqs = new javax.swing.JButton();
        jPanel19 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jPanel20 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnMaintenanceRequests.setText("Check Maintenance Request");
        btnMaintenanceRequests.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMaintenanceRequestsActionPerformed(evt);
            }
        });
        add(btnMaintenanceRequests, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 140, -1, -1));

        btnCheckAgentReqs.setText("Check Agent Requests");
        btnCheckAgentReqs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCheckAgentReqsActionPerformed(evt);
            }
        });
        add(btnCheckAgentReqs, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 180, 220, -1));

        jPanel19.setBackground(new java.awt.Color(0, 4, 68));

        jLabel18.setFont(new java.awt.Font("Al Tarikh", 1, 24)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("MANAGE REQUESTS");

        jPanel20.setBackground(new java.awt.Color(0, 102, 153));

        javax.swing.GroupLayout jPanel20Layout = new javax.swing.GroupLayout(jPanel20);
        jPanel20.setLayout(jPanel20Layout);
        jPanel20Layout.setHorizontalGroup(
            jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );
        jPanel20Layout.setVerticalGroup(
            jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel19Layout = new javax.swing.GroupLayout(jPanel19);
        jPanel19.setLayout(jPanel19Layout);
        jPanel19Layout.setHorizontalGroup(
            jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel19Layout.createSequentialGroup()
                .addComponent(jPanel20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel18)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addContainerGap(1121, Short.MAX_VALUE))
        );
        jPanel19Layout.setVerticalGroup(
            jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel19Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel19Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(8, 8, 8)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        add(jPanel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1390, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnMaintenanceRequestsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMaintenanceRequestsActionPerformed
        // TODO add your handling code here:
        ViewMaintenanceRequests viewMaintenanceRequests = new ViewMaintenanceRequests(userProcessContainer, organization,enterprise,network, userAccount);
        userProcessContainer.add("viewMaintenanceRequests", viewMaintenanceRequests);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnMaintenanceRequestsActionPerformed

    private void btnCheckAgentReqsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCheckAgentReqsActionPerformed
        // TODO add your handling code here:
        ViewAgentRequestJPanel agentRequestJPanel = new ViewAgentRequestJPanel(userProcessContainer, organization,enterprise,network, userAccount);
        userProcessContainer.add("agentRequestJPanel", agentRequestJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnCheckAgentReqsActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCheckAgentReqs;
    private javax.swing.JButton btnMaintenanceRequests;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel20;
    // End of variables declaration//GEN-END:variables
}
