/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.RealEstateAdminRole;

import Business.Enterprise.Enterprise;
import Business.Enterprise.RealEstateDirectory;
import Business.Government;
import Business.Organization.Organization;
import Business.Enterprise.EnterpriseDirectory;
import Business.Network.Network;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author kanikamakhija
 */
public class RealEstateMainJPanel extends javax.swing.JPanel {
    private final UserAccount userAccount;

    /**
     * Creates new form RealEstateMainJPanel
     */
    Government govt;
    private final Organization organization;
    Enterprise enterprise;
    JPanel userProcessContainer;
    private final Network network;
   
    /**
     *
     * @param userProcessContainer
     * @param organization
     * @param enterprise
     * @param network
     * @param userAccount
     * @param govt
     */
    public RealEstateMainJPanel(JPanel userProcessContainer, Organization organization, Enterprise enterprise, Network network, UserAccount userAccount, Government govt) {
        initComponents();
        //this.govt=govt;
        //this.realesatedirectory=realesatedirectory;
        this.userProcessContainer=userProcessContainer;
        this.organization = organization;
        this.enterprise = enterprise;
        this.network = network;
        this.userAccount = userAccount;
        this.govt = govt;
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        createReqBtn = new javax.swing.JButton();
        chkStatusBtn = new javax.swing.JButton();
        userNameJTextField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        passwordField = new javax.swing.JTextField();
        loginJButton = new javax.swing.JButton();
        logoutJButton = new javax.swing.JButton();
        frgtPswdBtn = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        createReqBtn.setText("Create New Real Estate Request");
        createReqBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createReqBtnActionPerformed(evt);
            }
        });
        add(createReqBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 346, -1, -1));

        chkStatusBtn.setText("Check Request Status");
        chkStatusBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkStatusBtnActionPerformed(evt);
            }
        });
        add(chkStatusBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 387, 241, -1));
        add(userNameJTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(462, 139, 196, -1));

        jLabel2.setText("User Name");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(116, 145, 117, -1));

        jLabel3.setText("Password");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(116, 185, 117, -1));
        add(passwordField, new org.netbeans.lib.awtextra.AbsoluteConstraints(462, 179, 196, -1));

        loginJButton.setText("Login");
        loginJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginJButtonActionPerformed(evt);
            }
        });
        add(loginJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 267, -1, -1));

        logoutJButton.setText("Logout");
        add(logoutJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(298, 267, -1, -1));

        frgtPswdBtn.setText("Forgot Password?");
        add(frgtPswdBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(505, 267, -1, -1));

        jPanel7.setBackground(new java.awt.Color(0, 0, 153));

        jPanel8.setBackground(new java.awt.Color(0, 153, 204));

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel9.setBackground(new java.awt.Color(0, 153, 204));

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 1066, Short.MAX_VALUE)
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 79, 1106, -1));

        jPanel10.setBackground(new java.awt.Color(0, 4, 68));

        jLabel14.setFont(new java.awt.Font("Al Tarikh", 1, 24)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("REAL ESTATE ADMINISTRATOR");

        jPanel11.setBackground(new java.awt.Color(0, 153, 204));

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 12, Short.MAX_VALUE)
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 569, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(773, Short.MAX_VALUE))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1380, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void loginJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginJButtonActionPerformed
        
//        RealEstateAdminJPanel repi = new RealEstateAdminJPanel(this.userProcessContainer);
//        this.userProcessContainer.add("realestatemainpanel",repi);
//        CardLayout layout =(CardLayout)this.userProcessContainer.getLayout();
//        layout.next(userProcessContainer);
        
        // Get user name
//        String userName = userNameJTextField.getText();
//        // Get Password
//        char[] passwordCharArray = passwordField.getPassword();
//        String password = String.valueOf(passwordCharArray);
        
//        //Step1: Check in the system admin user account directory if you have the user
//        UserAccount userAccount=system.getUserAccountDirectory().authenticateUser(userName, password);
//        
//        Enterprise inEnterprise=null;
//        Organization inOrganization=null;
//        
//        if(userAccount==null){
//            //Step 2: Go inside each network and check each enterprise
//            for(Network network:system.getNetworkList()){
//                //Step 2.a: check against each enterprise
//                for(Enterprise enterprise:network.getEnterpriseDirectory().getEnterpriseList()){
//                    userAccount=enterprise.getUserAccountDirectory().authenticateUser(userName, password);
//                    if(userAccount==null){
//                       //Step 3:check against each organization for each enterprise
//                       for(Organization organization:enterprise.getOrganizationDirectory().getOrganizationList()){
//                           userAccount=organization.getUserAccountDirectory().authenticateUser(userName, password);
//                           if(userAccount!=null){
//                               inEnterprise=enterprise;
//                               inOrganization=organization;
//                               break;
//                           }
//                       }
//                        
//                    }
//                    else{
//                       inEnterprise=enterprise;
//                       break;
//                    }
//                    if(inOrganization!=null){
//                        break;
//                    }  
//                }
//                if(inEnterprise!=null){
//                    break;
//                }
//            }
//        }
//        
//        if(userAccount==null){
//            JOptionPane.showMessageDialog(null, "Invalid credentials");
//            return;
//        }
//        else{
//            CardLayout layout=(CardLayout)container.getLayout();
//            container.add("workArea",userAccount.getRole().createWorkArea(container, userAccount, inOrganization, inEnterprise, system));
//            layout.next(container);
//        }
        
//        loginJButton.setEnabled(false);
//        logoutJButton.setEnabled(true);
//        userNameJTextField.setEnabled(false);
//        passwordField.setEnabled(false);
         
    }//GEN-LAST:event_loginJButtonActionPerformed

    private void createReqBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createReqBtnActionPerformed
        // TODO add your handling code here:
//         RealEstatePersonalInfoJPanel repi = new RealEstatePersonalInfoJPanel(this.userProcessContainer,this.enterprise);
//        this.userProcessContainer.add("realestatemainpanel",repi);
//        CardLayout layout =(CardLayout)this.userProcessContainer.getLayout();
//        layout.next(userProcessContainer);
    }//GEN-LAST:event_createReqBtnActionPerformed

    private void chkStatusBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkStatusBtnActionPerformed
        // TODO add your handling code here:
//        RealEstateCheckStatusJPanel statusJPanel = new RealEstateCheckStatusJPanel(userProcessContainer, this.enterprise);
//        this.userProcessContainer.add("RealEstateCheckStatusJPanel",statusJPanel);
//        CardLayout layout =(CardLayout)this.userProcessContainer.getLayout();
//        layout.next(userProcessContainer);
    }//GEN-LAST:event_chkStatusBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton chkStatusBtn;
    private javax.swing.JButton createReqBtn;
    private javax.swing.JButton frgtPswdBtn;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JButton loginJButton;
    private javax.swing.JButton logoutJButton;
    private javax.swing.JTextField passwordField;
    private javax.swing.JTextField userNameJTextField;
    // End of variables declaration//GEN-END:variables
}
